---

- hosts: 8.8.8.8 
  become: yes
  vars:
    myvar1: git
    myvar2: tree

  tasks: 
  - name: display var1
    debug:
      msg: "{{myvar1}}"

  - name: execute linux command module
    command: hostname
    register: myresult    # here register stores the result of the command

  - name: display myresult
    debug:
      msg: "{{myresult}}"

  - name: install git
    apt:
      name: git
      state: present
    when: myresult.stderr==""   # based on myresult value git will be installed

    

 